export const SliderSetting = {
  dots: true,
  infinite: true,
  speed: 500,
  slidesToShow: 1,
  slidesToScroll: 1
};
export const images = [
  {url: "/images/1.jpeg"}
]

/*  {url: "../images/スライド2.jpg"},
  {url: "../images/スライド3.jpg"},
  {url: "../images/スライド4.jpg"},
  {url: "../images/スライド5.jpg"},
  {url: "../images/スライド6.jpg"},
  {url: "../images/スライド7.jpg"},
  {url: "../images/スライド8.jpg"},
  {url: "../images/スライド9.jpg"},
  {url: "../images/スライド10.jpg"},
  {url: "../images/スライド11.jpg"},
  {url: "../images/スライド12.jpg"},
  {url: "../images/スライド13.jpg"},
  {url: "../images/スライド14.jpg"},
  {url: "../images/スライド15.jpg"},
  {url: "../images/スライド16.jpg"},
  {url: "../images/スライド17.jpg"},
  {url: "../images/スライド18.jpg"},
  {url: "../images/スライド19.jpg"},
  {url: "../images/スライド20.jpg"},
  {url: "../images/スライド21.jpg"},
  {url: "../images/スライド22.jpg"},
  {url: "../images/スライド23.jpg"},
  {url: "../images/スライド24.jpg"},
  {url: "../images/スライド25.jpg"},
  {url: "../images/スライド26.jpg"},
  {url: "../images/スライド27.jpg"},
  {url: "../images/スライド28.jpg"},
  {url: "../images/スライド29.jpg"},
  {url: "../images/スライド30.jpg"},
  {url: "../images/スライド31.jpg"},
  {url: "../images/スライド32.jpg"},
  {url: "../images/スライド33.jpg"},
  {url: "../images/スライド34.jpg"},
  {url: "../images/スライド35.jpg"},
  {url: "../images/スライド36.jpg"},
  {url: "../images/スライド37.jpg"},
  {url: "../images/スライド38.jpg"},*/
